Repository aniketsen123/Mvvm_newsapp, pull requests merged in 2023-02, with the labels that each got.

#8 Debojyoti
  .idea/gradle.xml
  .idea/vcs.xml
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/img.png
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: Easy, JWOC

#10 ⭐ Update Toolbar and UI
  .idea/misc.xml
  app/src/main/res/drawable-v24/heading_bg.xml
  app/src/main/res/layout/activity_news.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: JWOC, Medium

#12 🪲 BUG REMOVE: Download Button
  README.md
Labels: bug, JWOC, Medium

#17 Item_Article_Preview Updated
  app/src/main/res/layout/fragment_breaking_news.xml
  app/src/main/res/layout/item_article_preview.xml
Labels: JWOC, Medium

#16 Update readme file
  README.md
Labels: JWOC, Medium

#21 Updated the readme file
  README.md
Labels: Easy, JWOC
